### ISSUE TITLE
关于扩展方法的注解和内联

### ISSUE THREAD

**Issue by Quyunshuo** [hi-dhl/KtKit#1]
我看了下大佬的代码，每个扩展都添加了 `@kotlin.internal.InlineOnly` 注解和 `inline` 关键字，能不能讲一下这么写的好处，我不太明白

**Comment by Quyunshuo** [comment]
我在知乎上看到这么一段话
> Kotlin 并不建议将非高阶函数定义为内联函数：
> ```kotlin
> inline fun foo() = println("foo")
> ```
> 编译，Kotlin 编译器会给我们一个警告：
>```
> Warning:(1, 1) 
> Kotlin: Expected performance impact of inlining 'public inline fun foo(): Unit defined in root package' can be insignificant. 
> Inlining works best for functions with lambda parameters
> ```
> 编译器告诉我们，内联最好与有 Lambda 表达式参数的函数配合使用，内联这里的 foo() 函数对性能的影响微乎其微。

**Comment by hi-dhl** [comment]
Inline ([内联函数](https://www.kotlincn.net/docs/reference/inline-functions.html)) 的作用：提升运行效率，调用被 inline 修饰符的函数，会把里面的代码放到我调用的地方。

Inline 修饰符适用于下面两种情况，编译器才不会有警告

* 将函数类型作为参数
* 结合  reified 实化类型参数参数

很多扩展方法代码段很短，使用 Inline 修饰符， 将方法体的代码段放到调用处，来提升性能（虽然微乎其微），但是编译器会给出警告，所以添加 InlineOnly 注解有以下作用

* 消除警告
* 修改内联函数的可见性，默认是public,  加上修饰符，编译时改成 private

**Comment by Quyunshuo** [comment]
学习了

**Comment by hi-dhl** [comment]
Inline ([内联函数](https://www.kotlincn.net/docs/reference/inline-functions.html)) 的作用：提升运行效率，调用被 inline 修饰符的函数，会把里面的代码放到我调用的地方。

Inline 修饰符用于下面的情况，编译器才不会有警告：

* 将函数作为参数
* 结合 reified 实化类型参数一起使用

很多扩展方法代码段很短，使用 Inline 修饰符， 将方法体的代码段放到调用处，来提升性能（虽然微乎其微），但是编译器会给出警告，所以添加 InlineOnly 注解有以下作用

* 消除编译给出警告
* 修改内联函数的可见性，在编译时修改成 private
