### ISSUE TITLE
View.clickTrigger的BUG

### ISSUE THREAD

**Issue by HuanXiaoJue** [hi-dhl/KtKit#11]
![1632640389(1)](https://user-images.githubusercontent.com/34411011/134797710-c05207a9-8edf-48a5-9e74-25eb33cea810.png)
圈中的代码只会在第一次调用View.clickTrigger时候生效，想要实现防抖要放到onEach里面

**Comment by hi-dhl** [comment]
感谢反馈，已经提交，修复了
