### ISSUE TITLE
./gradlew spotlessApply 命令运行不了

### ISSUE THREAD

**Issue by ZakAnun** [hi-dhl/KtKit#4]
### 现象
在执行 `./gradlew spotlessApply` 这个命令的时候提示 `Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

### 原因
估计是 .gitignore 文件中将 jar 包排除在版本管理外导致项目中根目录下的 gradle 目录中缺失了 `gradle-wrapper.jar` 而出现的运行错误

### 处理
拷了一份 `gradle-wrapper.jar` 到该目录下后运行成功，建议将它添加回去。

**Comment by hi-dhl** [comment]
这个 jar 应该会自动生成的，我看一下

**Comment by hi-dhl** [comment]
非常感谢你的反馈，gradle-wrapper.jar 已经更新了，我将要关闭这 issue, 欢迎再次提 issue
