### ISSUE TITLE
关于view的操作的bug

### ISSUE THREAD

**Issue by HolmesBill** [hi-dhl/KtKit#6]
view.visible()
我看源码这里是返回一个VIew.VISIBLE，是一个Int类型，并不能改变view，这里应该是一个bug吧
应该写成
inline fun View.visible() {
       setVisibility(View.VISIBLE)
}

**Comment by Quyunshuo** [comment]
> view.visible()
> 我看源码这里是返回一个VIew.VISIBLE，是一个Int类型，并不能改变view，这里应该是一个bug吧
> 应该写成
> inline fun View.visible() {
> setVisibility(View.VISIBLE)
> }

起初我以为是作者有其他用意，我看了下文档确定可能是作者写的时候没有注意，我修改了这个问题提交了PR

**Comment by hi-dhl** [comment]
@HolmesBill  @Quyunshuo  感谢反馈和提交 PR 已经合入
